

- name: Levantar el Servidor NTP Maestro de la Planta
  containers.podman.podman_container:
    name: servidor-ntp
    image: alpine
    state: started
    restart_policy: always
    network: red-dmz
    # Arranca solo el demonio NTP, escucha en red (-l) y se sincroniza con internet (-p)
    command: ntpd -n -l -I red-dmz -p pool.ntp.org