
- name: "Node-RED | Init"
  hosts: all
  become: true
  gather_facts: yes
  roles:
  - { role: node-red, tags: ['node-red'] }

- name: "PLC | Init"
  hosts: all
  become: true
  gather_facts: yes
  roles:
  - { role: plc, tags: ['plc'] }

- name: "Monitor | Weavescope"
  hosts: all
  gather_facts: false
  roles:
  - { role: monitor, tags: ['monitor'] }