- name: 1. Asegurar que el socket de Podman del usuario está activo y habilitado
  ansible.builtin.systemd:
    name: podman.socket
    scope: user
    enabled: yes
    state: started
  become: yes
  become_user: debian-dev

- name: 2. Desplegar el contenedor de Weave Scope mediante Podman
  containers.podman.podman_container:
    name: weavescope
    image: "weaveworks/scope:latest"
    state: started
    restart_policy: always
    # Eliminamos network_mode: host y pid: host para evitar bloqueos de privilegios
    privileged: yes
    # MAPEO EXPLÍCITO: Vinculamos el puerto 8081 de tu PC al 4040 interno de Scope
    ports:
      - "8081:4040"
    volumes:
      - "/run/user/1000/podman/podman.sock:/var/run/docker.sock:Z"
    command:
      - "--probe.docker=true"
      - "--probe.kubernetes=false"
      - "--weave=false"
  become: yes
  become_user: debian-dev