---
- name: Crear directorio para el compose de Scope
  file:
    path: /opt/weavescope
    state: directory
    mode: '0755'

- name: Asegurar que no existan contenedores previos con el mismo nombre
  docker_container:
    name: weavescope
    state: absent

- name: Desplegar template de Docker Compose
  template:
    src: pcompose-weavescope.yml.j2
    dest: /opt/weavescope/podman-compose.yml
    mode: '0644'

- name: Levantar el contenedor de Weave Scope con podman-compose (CLI)
  command:
    cmd: podman-compose up -d
    chdir: /opt/weavescope
  register: podman_compose_result
  changed_when: "'Creating' in podman_compose_result.stdout or 'Configuring' in podman_compose_result.stdout"