---
- name: 1. Asegurar que el socket de Podman del usuario está activo y habilitado
  ansible.builtin.systemd:
    name: podman.socket
    scope: user
    enabled: yes
    state: started
  become: yes
  become_user: debian-dev

- name: "1.5. Corregir y asegurar propiedad de la carpeta base de servicios"
  ansible.builtin.file:
    path: "/home/debian-dev/services"
    state: directory
    owner: debian-dev
    group: debian-dev
    mode: '0755'
  become: yes  # Ejecuta como root para poder cambiar el dueño si estuviera bloqueado

- name: "2. Asegurar directorio de destino para los servicios (portainer / weavescope)"
  ansible.builtin.file:
    path: "/home/debian-dev/services/{{ (item | ansible.builtin.basename | ansible.builtin.splitext | first | ansible.builtin.regex_replace('\\.yml$', '')) | ansible.builtin.regex_replace('^p-?compose[-.]', '') }}"
    state: directory
    mode: '0755'
    owner: debian-dev
    group: debian-dev
  loop: "{{ query('ansible.builtin.fileglob', role_path ~ '/templates/pcompose*.yml.j2') }}"
  become: yes
  become_user: debian-dev

- name: "3. Procesar plantilla Jinja2 y generar el podman-compose.yml"
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/home/debian-dev/services/{{ (item | ansible.builtin.basename | ansible.builtin.splitext | first | ansible.builtin.regex_replace('\\.yml$', '')) | ansible.builtin.regex_replace('^p-?compose[-.]', '') }}/podman-compose.yml"
    mode: '0644'
  loop: "{{ query('ansible.builtin.fileglob', role_path ~ '/templates/pcompose*.yml.j2') }}"
  become: yes
  become_user: debian-dev

- name: "4. Levantar servicios con podman-compose"
  ansible.builtin.command:
    cmd: "podman-compose up -d"
    chdir: "/home/debian-dev/services/{{ (item | ansible.builtin.basename | ansible.builtin.splitext | first | ansible.builtin.regex_replace('\\.yml$', '')) | ansible.builtin.regex_replace('^p-?compose[-.]', '') }}"
  register: compose_output
  changed_when: "'Creating' in compose_output.stdout or 'Starting' in compose_output.stdout"
  loop: "{{ query('ansible.builtin.fileglob', role_path ~ '/templates/pcompose*.yml.j2') }}"
  become: yes
  become_user: debian-dev