---
# ==========================================================
# TAREA 1: CREACIÓN DINÁMICA DE REDES (SWITCHES)
# ==========================================================
- name: "1. Crear las redes dinámicamente según tu diccionario flota_plc"
  containers.podman.podman_network:
    name: "{{ item.key }}"
    driver: bridge
    internal: true # Mantenemos el aislamiento OT estricto (IEC 62443)
  become: yes
  become_user: debian-dev
  loop: "{{ flota_plc | dict2items }}"

# ==========================================================
# TAREA 2: DESPLIEGUE ANIDADO DE PLCS CON IP FIJA
# ==========================================================
- name: "2. Bucle Anidado: Por cada red, levantar sus activos con IP estática"
  containers.podman.podman_container:
    name: "{{ item.1.nombre }}"                     # Accede al campo 'nombre' del objeto
    image: "localhost/openplc-local:latest"
    state: started
    restart_policy: always
    network: "{{ item.0.key }}"                     # Nombre de la red (red_industrial_1, etc.)
    ip: "{{ item.1.ip_fija }}"                      # INYECCIÓN DE LA IP FIJA INDUSTRIAL
    
    # Mapeo dinámico de puertos adaptado a la nueva estructura de objetos
    expose:
      - "8080"
      - "502"
    ports:
      - "{{ 9001 + lista_plcs_plana.index(item.1.nombre) }}:8080"
      - "{{ 5020 + lista_plcs_plana.index(item.1.nombre) }}:502"
  become: yes
  become_user: debian-dev
  # Subelements ahora itera sobre la lista 'value.dispositivos' de cada red
  loop: "{{ q('ansible.builtin.subelements', flota_plc | dict2items, 'value.dispositivos') }}"
  vars:
    # Generamos la lista plana de nombres extrayendo solo el campo 'nombre' para mantener tu cálculo de puertos
    lista_plcs_plana: "{{ flota_plc.values() | map(attribute='dispositivos') | flatten | map(attribute='nombre') | list }}"