
- name: "Asegurar que el directorio del firewall existe en el host"
  ansible.builtin.file:
    path: /home/debian-dev/etap/firewall
    state: directory
    mode: '0755'
    owner: debian-dev  # Forzamos que el dueño sea tu usuario dev
    group: debian-dev

- name: Levantar el contenedor Firewall de Zona
  containers.podman.podman_container:
    name: "{{ item.name }}"
    image: alpine
    state: started
    restart_policy: always
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_TIME
    network:
      - red-dmz
      - "{{ item.networks }}"
    volume:
      - "/home/debian-dev/etap/firewall:/opt/firewall:Z"
    command:
      - sh
      - -c
      - ntpd -q -p servidor-ntp && /opt/firewall/rules.sh && tail -f /dev/null
  become: false
  loop:
    - name: fw-entrada
      networks: [red-entrada]
    - name: fw-pretratamiento
      networks: [red-pretratamiento]
    - name: fw-tanque-mezcla
      networks: [red-tanque-mezcla]
    - name: fw-decantador
      networks: [red-decantador]
    - name: fw-desinfeccion
      networks: [red-desinfeccion]
    - name: fw-dmz
      networks: [red-dmz]